name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i # There is a bug with npm ci -> https://github.com/npm/cli/issues/558
      - run: npm run coverage
      - name: Upload coverage file to Coveralls using lcov.info
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}